import type { NFT, User, Transaction, Collection } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    username: "cryptoartist",
    displayName: "Crypto Artist",
    avatar: "/artist-avatar.png",
    bio: "Digital artist creating unique NFTs on Flow",
    walletAddress: "0x1234...5678",
    verified: true,
    joinedAt: "2024-01-15",
    nftsOwned: 24,
    nftsCreated: 12,
  },
  {
    id: "2",
    username: "collector_pro",
    displayName: "Pro Collector",
    avatar: "/collector-avatar.png",
    bio: "Passionate NFT collector and trader",
    walletAddress: "0xabcd...efgh",
    verified: true,
    joinedAt: "2024-02-20",
    nftsOwned: 156,
    nftsCreated: 3,
  },
  {
    id: "3",
    username: "nft_creator",
    displayName: "NFT Creator",
    avatar: "/creator-avatar.png",
    bio: "Creating the future of digital art",
    walletAddress: "0x9876...5432",
    verified: false,
    joinedAt: "2024-03-10",
    nftsOwned: 8,
    nftsCreated: 45,
  },
]

export const mockNFTs: NFT[] = [
  {
    id: "1",
    name: "Cosmic Dreams #001",
    description: "A mesmerizing journey through the cosmos, captured in digital form.",
    image: "/cosmic-space-art.png",
    price: 0.5,
    currency: "FLOW",
    owner: mockUsers[1],
    creator: mockUsers[0],
    category: "Art",
    rarity: "legendary",
    mintedAt: "2024-03-15T10:30:00Z",
    views: 1234,
    likes: 89,
    blockchain: "Flow",
    tokenId: "A.1234.NFT.001",
    royalty: 10,
  },
  {
    id: "2",
    name: "Digital Sunset",
    description: "Where technology meets nature in perfect harmony.",
    image: "/digital-sunset-landscape.jpg",
    price: 0.25,
    currency: "FLOW",
    owner: mockUsers[0],
    creator: mockUsers[0],
    category: "Photography",
    rarity: "rare",
    mintedAt: "2024-03-14T15:20:00Z",
    views: 856,
    likes: 67,
    blockchain: "Flow",
    tokenId: "A.1234.NFT.002",
    royalty: 5,
  },
  {
    id: "3",
    name: "Abstract Thoughts",
    description: "An exploration of form and color in the digital realm.",
    image: "/abstract-geometric-art.png",
    price: 0.75,
    currency: "FLOW",
    owner: mockUsers[2],
    creator: mockUsers[2],
    category: "Art",
    rarity: "epic",
    mintedAt: "2024-03-13T09:15:00Z",
    views: 2341,
    likes: 156,
    blockchain: "Flow",
    tokenId: "A.1234.NFT.003",
    royalty: 7.5,
  },
  {
    id: "4",
    name: "Neon City #42",
    description: "Cyberpunk aesthetics meet blockchain technology.",
    image: "/neon-cyberpunk-city.png",
    price: 1.2,
    currency: "FLOW",
    owner: mockUsers[1],
    creator: mockUsers[0],
    category: "Digital Art",
    rarity: "legendary",
    mintedAt: "2024-03-12T18:45:00Z",
    views: 3456,
    likes: 234,
    blockchain: "Flow",
    tokenId: "A.1234.NFT.004",
    royalty: 10,
  },
  {
    id: "5",
    name: "Minimalist Wave",
    description: "Less is more in this stunning minimalist piece.",
    image: "/minimalist-wave-art.jpg",
    price: 0.3,
    currency: "FLOW",
    owner: mockUsers[0],
    creator: mockUsers[2],
    category: "Art",
    rarity: "common",
    mintedAt: "2024-03-11T12:00:00Z",
    views: 567,
    likes: 45,
    blockchain: "Flow",
    tokenId: "A.1234.NFT.005",
    royalty: 5,
  },
  {
    id: "6",
    name: "Glitch Reality",
    description: "When reality glitches, art emerges.",
    image: "/glitch-art-digital.jpg",
    price: 0.45,
    currency: "FLOW",
    owner: mockUsers[2],
    creator: mockUsers[0],
    category: "Digital Art",
    rarity: "rare",
    mintedAt: "2024-03-10T14:30:00Z",
    views: 1123,
    likes: 78,
    blockchain: "Flow",
    tokenId: "A.1234.NFT.006",
    royalty: 7.5,
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    type: "sale",
    nft: mockNFTs[0],
    from: mockUsers[0],
    to: mockUsers[1],
    price: 0.5,
    currency: "FLOW",
    timestamp: "2024-03-15T10:35:00Z",
    txHash: "0xabc123...",
    status: "completed",
  },
  {
    id: "2",
    type: "mint",
    nft: mockNFTs[1],
    from: mockUsers[0],
    to: mockUsers[0],
    timestamp: "2024-03-14T15:20:00Z",
    txHash: "0xdef456...",
    status: "completed",
  },
]

export const mockCollections: Collection[] = [
  {
    id: "1",
    name: "Cosmic Series",
    description: "A collection exploring the vastness of space",
    image: "/cosmic-collection.jpg",
    creator: mockUsers[0],
    nfts: [mockNFTs[0], mockNFTs[3]],
    floorPrice: 0.5,
    volume: 12.5,
    items: 10,
  },
]
