name: Flow Emulator Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  flow-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Flow CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify Flow CLI installation
      run: flow version

    - name: Install dependencies
      run: npm ci

    - name: Run Flow emulator tests
      run: npm run test:flow
      timeout-minutes: 10

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: flow-test-results
        path: |
          coverage/
          test-results/
        retention-days: 7